export const copy = {
  common: {
    status: '状态',
    connected: '已连接',
    unavailable: '不可用',
    loading: '加载中',
    refresh: '刷新',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    database: '数据库',
    collection: '集合',
    document: '文档',
    actions: '操作',
    currentPage: '当前页',
  },
  sidebar: {
    eyebrow: '控制台',
    title: '数据库视图',
    createCollection: '+ 新建集合',
    collectionCount: (count: number) => `${count} 个集合`,
    collectionTag: '集合',
  },
  editor: {
    eyebrow: '文档编辑器',
    hint:
      '如需写入 BSON 特殊类型，请使用 MongoDB Extended JSON，例如 { "$oid": "..." } 或 { "$date": "2024-01-01T00:00:00Z" }。',
    placeholder: '{\n  "name": "示例"\n}',
    invalidJson: 'JSON 格式不合法，请检查后重试',
  },
  docs: {
    eyebrow: '接口文档',
    title: 'OpenAPI 接口契约',
    summary: '后端会以 JSON 形式公开当前 API 契约，便于联调、排障和后续并入运维平台。',
  },
  dashboard: {
    fallbackCluster: '默认集群',
    fallbackHost: '本地实例',
    heroEyebrow: 'MongoDB 运维台',
    heroTitle: '面向运维场景的数据操作工作区',
    heroSummary: '集中浏览数据库与集合，执行文档 CRUD，并用 JSON 查询快速完成排障和日常维护。',
    metricDatabases: '数据库数量',
    metricVisibleDocuments: '当前文档数',
    metricRoundTrip: '往返延迟',
    clusterHealth: '集群健康状态',
    openApiDocs: '查看接口文档',
    newDocument: '新建文档',
    newCollection: '新建集合',
    connectedDatabase: '当前连接数据库',
    serverVersion: '服务版本',
    selection: '当前选择',
    totalHits: '命中总数',
    queryEyebrow: '查询面板',
    queryTitle: '文档流',
    filterPlaceholder: '输入严格 JSON 过滤条件，例如 {"status":"active"}',
    runQuery: '执行查询',
    deleteCollection: '删除集合',
    sort: '排序',
    project: '投影',
    maxTime: '最长 10 秒',
    strictJsonOnly: '仅支持严格 JSON',
    perPage: (count: number) => `每页 ${count} 条`,
    totalDocuments: (count: number) => `共 ${count} 条文档`,
    noCollectionSelected: '未选择集合',
    emptySelectionTitle: '请先从左侧选择一个集合',
    emptySelectionHint: '选中后即可查看文档列表、执行查询并进行增删改操作。',
    queryFailed: '查询失败',
    emptyCollectionTitle: '当前集合没有文档',
    emptyCollectionHint: '你可以先创建第一条文档，或者调整 JSON 过滤条件后重新查询。',
    addFirstDocument: '创建第一条文档',
    notesEyebrow: '操作说明',
    notesTitle: '当前数据上下文',
    chooseFromSidebar: '请从左侧选择',
    jsonFilter: 'JSON 过滤条件',
    extendedJsonHint: '如需写入 ObjectId、Date 等 BSON 特殊值，请在编辑器中使用 Extended JSON。',
    indexUsage: '索引利用率',
    avgQueryTime: '平均查询耗时',
    storageSize: '估算存储量',
    optimizedForCollectionSize: '按当前集合规模估算',
    estimatedFromCurrentResultSet: '基于当前结果集估算',
    newDocumentIn: (title: string) => `在 ${title} 中新建文档`,
    editDocument: (id: string) => `编辑文档 ${id}`,
    createCollectionPrompt: (database: string) => `在 ${database} 中创建新集合`,
    createCollectionTitle: '新建集合',
    createCollectionConfirm: '创建',
    createCollectionSuccess: '集合创建成功',
    selectDatabaseFirst: '请先选择数据库',
    invalidFilter: '过滤条件必须是合法的严格 JSON，例如 {"status":"active"}。',
    invalidObjectId: '当前文档缺少合法的 ObjectId',
    documentUpdated: '文档更新成功',
    documentCreated: '文档创建成功',
    documentDeleted: '文档删除成功',
    collectionDeleted: '集合删除成功',
    deleteDocumentConfirm: (id: string) => `确认删除文档 ${id} 吗？`,
    deleteDocumentTitle: '删除文档',
    deleteCollectionConfirm: (database: string, collection: string) => `确认删除集合 ${database}.${collection} 吗？`,
    deleteCollectionTitle: '删除集合',
  },
  http: {
    requestFailed: '请求失败',
  },
} as const
